name: Release Hello World Actor

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.1.0, v1.2.3, etc.

jobs:
  release:
    uses: ./.github/workflows/reusable-actor-release.yml
    with:
      actor-name: "hello-world"
    permissions:
      contents: write
